import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "./ui/card";
import { Badge } from "./ui/badge";
import { Button } from "./ui/button";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "./ui/dialog";
import { ScrollArea } from "./ui/scroll-area";
import { Sparkles, MapPin, IndianRupee, Calendar, Share2, Download, Shield, Zap, Users, BarChart3, Wifi, TrendingUp, Clock, ChevronLeft, ChevronRight } from "lucide-react";

const innovationFeatures = [
  {
    icon: Clock,
    title: "Crowd & Queue Predictor",
    description: "AI-powered crowd analysis shows best visiting times and real-time queue lengths at popular attractions",
    highlight: "Smart Timing",
    category: "Innovation",
    details: {
      overview: "Our advanced AI analyzes historical data, social media trends, and real-time feeds to predict crowd levels at tourist attractions across India.",
      benefits: [
        "Avoid long queues at popular monuments like Taj Mahal",
        "Get optimal visiting times for temples and historical sites", 
        "Real-time crowd density updates",
        "Save 2-3 hours per day by timing visits perfectly"
      ],
      technology: "Machine Learning algorithms analyze visitor patterns, weather data, holidays, and events to provide 90% accurate crowd predictions."
    }
  },
  {
    icon: TrendingUp,
    title: "AI-Driven Replanning",
    description: "Dynamic itinerary adjustments based on weather, crowds, or personal preferences with one-click replanning",
    highlight: "Adaptive Planning",
    category: "Innovation", 
    details: {
      overview: "Revolutionary AI that instantly replans your entire itinerary when conditions change, ensuring you never miss the best experiences.",
      benefits: [
        "Instant replanning when weather changes",
        "Alternative routes during traffic or closures",
        "Backup indoor activities during monsoons",
        "Preference-based itinerary variations"
      ],
      technology: "Real-time data integration with weather APIs, traffic systems, and attraction status to provide intelligent replanning in under 30 seconds."
    }
  },
  {
    icon: Users,
    title: "Group Coordination Hub",
    description: "Collaborative planning with voting system, expense splitting, and real-time group consensus features",
    highlight: "Team Planning",
    category: "Innovation",
    details: {
      overview: "Complete group travel management system that handles everything from destination voting to expense tracking and bill splitting.",
      benefits: [
        "Democratic destination selection through voting",
        "Automatic expense splitting and tracking",
        "Group chat integration for planning",
        "Shared itinerary with individual customizations"
      ],
      technology: "Real-time collaboration engine with conflict resolution algorithms and intelligent expense categorization."
    }
  },
  {
    icon: BarChart3,
    title: "Dynamic Budget Analyzer",
    description: "Live spending tracking with AI suggestions for cheaper alternatives and budget optimization",
    highlight: "Smart Spending", 
    category: "Innovation",
    details: {
      overview: "Intelligent budget management that tracks your spending in real-time and provides instant money-saving recommendations.",
      benefits: [
        "Live spending vs budget tracking",
        "AI-suggested cheaper alternatives",
        "Local deals and discount integration",
        "Emergency budget rebalancing"
      ],
      technology: "Machine learning models analyze local pricing, seasonal variations, and user preferences to optimize spending without compromising experience."
    }
  },
  {
    icon: Wifi,
    title: "Offline Emergency Mode",
    description: "Complete offline access with downloadable maps, contacts, and itineraries for no-internet situations",
    highlight: "Always Connected",
    category: "Innovation",
    details: {
      overview: "Comprehensive offline functionality ensures you're never stranded without information, even in remote Indian destinations.",
      benefits: [
        "Offline downloadable itineraries with maps", 
        "Emergency contact numbers and services",
        "Offline translation for local languages",
        "GPS-enabled navigation without internet"
      ],
      technology: "Progressive Web App technology with advanced caching and offline-first architecture for reliable access anywhere in India."
    }
  },
  {
    icon: Sparkles,
    title: "AI-Powered Itineraries",
    description: "Get personalized travel plans generated by advanced AI that understands your preferences and budget",
    highlight: "Smart Recommendations",
    category: "Core"
  },
  {
    icon: MapPin,
    title: "50+ Indian Destinations", 
    description: "Explore curated destinations across India from the Himalayas to Kerala backwaters",
    highlight: "Complete Coverage",
    category: "Core"
  },
  {
    icon: IndianRupee,
    title: "Budget Calculator",
    description: "Get accurate cost estimates in INR for accommodation, transport, food, and activities", 
    highlight: "Transparent Pricing",
    category: "Core"
  }
];

export function Features() {
  const [selectedFeature, setSelectedFeature] = useState<any>(null);
  const [currentIndex, setCurrentIndex] = useState(0);

  const scrollToNext = () => {
    setCurrentIndex((prev) => Math.min(prev + 1, innovationFeatures.length - 3));
  };

  const scrollToPrev = () => {
    setCurrentIndex((prev) => Math.max(prev - 1, 0));
  };

  const openFeatureModal = (feature: any) => {
    setSelectedFeature(feature);
  };

  return (
    <section className="py-16 bg-background">
      <div className="container px-4 mx-auto">
        <div className="text-center mb-12">
          <h2 className="text-3xl md:text-4xl font-['Roboto_Slab'] font-bold mb-4">
            Why Choose TravelGenie?
          </h2>
          <p className="text-lg text-muted-foreground max-w-2xl mx-auto font-['Open_Sans']">
            Experience the future of travel planning with our AI-powered platform designed specifically for Indian destinations
          </p>
        </div>

        {/* Innovation Features - Horizontal Scroll */}
        <div className="mb-16">
          <div className="flex items-center justify-between mb-6">
            <h3 className="text-2xl font-['Roboto_Slab'] font-bold">Innovation & Uniqueness</h3>
            <div className="flex space-x-2">
              <Button
                variant="outline"
                size="icon"
                onClick={scrollToPrev}
                disabled={currentIndex === 0}
                className="h-8 w-8"
              >
                <ChevronLeft className="h-4 w-4" />
              </Button>
              <Button
                variant="outline"
                size="icon"
                onClick={scrollToNext}
                disabled={currentIndex >= innovationFeatures.length - 3}
                className="h-8 w-8"
              >
                <ChevronRight className="h-4 w-4" />
              </Button>
            </div>
          </div>

          <div className="relative overflow-hidden">
            <div 
              className="flex transition-transform duration-300 ease-in-out gap-6"
              style={{ transform: `translateX(-${currentIndex * 33.333}%)` }}
            >
              {innovationFeatures.map((feature, index) => {
                const Icon = feature.icon;
                return (
                  <Card 
                    key={index} 
                    className="relative group hover:shadow-lg transition-all duration-300 hover:-translate-y-1 cursor-pointer flex-shrink-0 w-[calc(33.333%-1rem)]"
                    onClick={() => openFeatureModal(feature)}
                  >
                    <CardHeader>
                      <div className="flex items-center justify-between mb-4">
                        <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center group-hover:bg-orange-200 transition-colors">
                          <Icon className="w-6 h-6 text-orange-600" />
                        </div>
                        {feature.category === "Innovation" && (
                          <Badge className="bg-gradient-to-r from-purple-500 to-pink-500 text-white">
                            NEW
                          </Badge>
                        )}
                      </div>
                      <Badge variant="secondary" className="w-fit text-xs mb-2">
                        {feature.highlight}
                      </Badge>
                      <CardTitle className="text-lg font-['Roboto_Slab']">
                        {feature.title}
                      </CardTitle>
                    </CardHeader>
                    <CardContent>
                      <p className="text-sm text-muted-foreground font-['Open_Sans']">
                        {feature.description}
                      </p>
                      <Button variant="ghost" className="mt-4 p-0 h-auto text-orange-600 hover:text-orange-700">
                        Learn More →
                      </Button>
                    </CardContent>
                  </Card>
                );
              })}
            </div>
          </div>
        </div>

        {/* Market Gap Section */}
        <div className="mb-16 bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-8">
          <div className="text-center mb-8">
            <h3 className="text-2xl font-['Roboto_Slab'] font-bold mb-4">
              What Makes TravelGenie Unique?
            </h3>
            <p className="text-muted-foreground">Features you won't find in other travel apps</p>
          </div>
          
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="text-center">
              <div className="w-16 h-16 bg-purple-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Clock className="w-8 h-8 text-purple-600" />
              </div>
              <h4 className="font-semibold mb-2">Real-time Crowd Prediction</h4>
              <p className="text-sm text-muted-foreground">No other app tells you exactly when to visit attractions to avoid crowds</p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-blue-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-8 h-8 text-blue-600" />
              </div>
              <h4 className="font-semibold mb-2">Dynamic AI Replanning</h4>
              <p className="text-sm text-muted-foreground">Instantly replan your entire trip when conditions change</p>
            </div>
            <div className="text-center">
              <div className="w-16 h-16 bg-green-100 rounded-full flex items-center justify-center mx-auto mb-4">
                <Users className="w-8 h-8 text-green-600" />
              </div>
              <h4 className="font-semibold mb-2">True Group Collaboration</h4>
              <p className="text-sm text-muted-foreground">Advanced voting, expense splitting, and consensus features for groups</p>
            </div>
          </div>
        </div>

        {/* Stats Section */}
        <div className="mt-16 bg-orange-50 rounded-2xl p-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            <div>
              <div className="text-3xl md:text-4xl font-bold text-orange-600 mb-2">6+</div>
              <div className="text-sm text-muted-foreground">Happy Travelers</div>
            </div>
            <div>
              <div className="text-3xl md:text-4xl font-bold text-orange-600 mb-2">50+</div>
              <div className="text-sm text-muted-foreground">Destinations</div>
            </div>
            <div>
              <div className="text-3xl md:text-4xl font-bold text-orange-600 mb-2">100+</div>
              <div className="text-sm text-muted-foreground">Itineraries Created</div>
            </div>
            <div>
              <div className="text-3xl md:text-4xl font-bold text-orange-600 mb-2">4.8⭐</div>
              <div className="text-sm text-muted-foreground">User Rating</div>
            </div>
          </div>
        </div>
      </div>

      {/* Feature Detail Modal */}
      <Dialog open={!!selectedFeature} onOpenChange={() => setSelectedFeature(null)}>
        <DialogContent className="max-w-2xl max-h-[80vh]">
          {selectedFeature && (
            <>
              <DialogHeader>
                <div className="flex items-center space-x-4">
                  <div className="w-12 h-12 bg-orange-100 rounded-lg flex items-center justify-center">
                    <selectedFeature.icon className="w-6 h-6 text-orange-600" />
                  </div>
                  <div>
                    <DialogTitle className="text-xl font-['Roboto_Slab']">
                      {selectedFeature.title}
                    </DialogTitle>
                    <Badge variant="secondary" className="mt-1">
                      {selectedFeature.highlight}
                    </Badge>
                  </div>
                </div>
              </DialogHeader>
              
              <ScrollArea className="max-h-[60vh]">
                <div className="space-y-6 pr-4">
                  <p className="text-muted-foreground">{selectedFeature.description}</p>
                  
                  {selectedFeature.details && (
                    <>
                      <div>
                        <h4 className="font-semibold mb-2">How It Works</h4>
                        <p className="text-sm text-muted-foreground">{selectedFeature.details.overview}</p>
                      </div>
                      
                      <div>
                        <h4 className="font-semibold mb-2">Key Benefits</h4>
                        <ul className="space-y-1">
                          {selectedFeature.details.benefits?.map((benefit: string, index: number) => (
                            <li key={index} className="text-sm text-muted-foreground flex items-center">
                              <div className="w-1.5 h-1.5 bg-orange-500 rounded-full mr-2"></div>
                              {benefit}
                            </li>
                          ))}
                        </ul>
                      </div>
                      
                      {selectedFeature.details.technology && (
                        <div>
                          <h4 className="font-semibold mb-2">Technology</h4>
                          <p className="text-sm text-muted-foreground">{selectedFeature.details.technology}</p>
                        </div>
                      )}
                    </>
                  )}
                </div>
              </ScrollArea>
            </>
          )}
        </DialogContent>
      </Dialog>
    </section>
  );
}